// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/geo-ip-record.proto

package mayton.bigdata.kafka.protobuf;

public final class GeoIpRecordOuterClass {
  private GeoIpRecordOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GeoIpRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:enot.telegram.GeoIpRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string trie_key = 1;</code>
     * @return The trieKey.
     */
    java.lang.String getTrieKey();
    /**
     * <code>string trie_key = 1;</code>
     * @return The bytes for trieKey.
     */
    com.google.protobuf.ByteString
        getTrieKeyBytes();

    /**
     * <code>int64 begin_ip = 2;</code>
     * @return The beginIp.
     */
    long getBeginIp();

    /**
     * <code>int64 end_ip = 3;</code>
     * @return The endIp.
     */
    long getEndIp();

    /**
     * <code>string cc = 4;</code>
     * @return The cc.
     */
    java.lang.String getCc();
    /**
     * <code>string cc = 4;</code>
     * @return The bytes for cc.
     */
    com.google.protobuf.ByteString
        getCcBytes();

    /**
     * <code>string country = 5;</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 5;</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>string region = 6;</code>
     * @return The region.
     */
    java.lang.String getRegion();
    /**
     * <code>string region = 6;</code>
     * @return The bytes for region.
     */
    com.google.protobuf.ByteString
        getRegionBytes();

    /**
     * <code>string city = 7;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 7;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional float lattitude = 8;</code>
     * @return Whether the lattitude field is set.
     */
    boolean hasLattitude();
    /**
     * <code>optional float lattitude = 8;</code>
     * @return The lattitude.
     */
    float getLattitude();

    /**
     * <code>optional float longitude = 9;</code>
     * @return Whether the longitude field is set.
     */
    boolean hasLongitude();
    /**
     * <code>optional float longitude = 9;</code>
     * @return The longitude.
     */
    float getLongitude();
  }
  /**
   * Protobuf type {@code enot.telegram.GeoIpRecord}
   */
  public static final class GeoIpRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:enot.telegram.GeoIpRecord)
      GeoIpRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GeoIpRecord.newBuilder() to construct.
    private GeoIpRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GeoIpRecord() {
      trieKey_ = "";
      cc_ = "";
      country_ = "";
      region_ = "";
      city_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GeoIpRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeoIpRecordOuterClass.internal_static_enot_telegram_GeoIpRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeoIpRecordOuterClass.internal_static_enot_telegram_GeoIpRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GeoIpRecordOuterClass.GeoIpRecord.class, GeoIpRecordOuterClass.GeoIpRecord.Builder.class);
    }

    private int bitField0_;
    public static final int TRIE_KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object trieKey_ = "";
    /**
     * <code>string trie_key = 1;</code>
     * @return The trieKey.
     */
    @java.lang.Override
    public java.lang.String getTrieKey() {
      java.lang.Object ref = trieKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trieKey_ = s;
        return s;
      }
    }
    /**
     * <code>string trie_key = 1;</code>
     * @return The bytes for trieKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrieKeyBytes() {
      java.lang.Object ref = trieKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trieKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BEGIN_IP_FIELD_NUMBER = 2;
    private long beginIp_ = 0L;
    /**
     * <code>int64 begin_ip = 2;</code>
     * @return The beginIp.
     */
    @java.lang.Override
    public long getBeginIp() {
      return beginIp_;
    }

    public static final int END_IP_FIELD_NUMBER = 3;
    private long endIp_ = 0L;
    /**
     * <code>int64 end_ip = 3;</code>
     * @return The endIp.
     */
    @java.lang.Override
    public long getEndIp() {
      return endIp_;
    }

    public static final int CC_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cc_ = "";
    /**
     * <code>string cc = 4;</code>
     * @return The cc.
     */
    @java.lang.Override
    public java.lang.String getCc() {
      java.lang.Object ref = cc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cc_ = s;
        return s;
      }
    }
    /**
     * <code>string cc = 4;</code>
     * @return The bytes for cc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCcBytes() {
      java.lang.Object ref = cc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object country_ = "";
    /**
     * <code>string country = 5;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 5;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object region_ = "";
    /**
     * <code>string region = 6;</code>
     * @return The region.
     */
    @java.lang.Override
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      }
    }
    /**
     * <code>string region = 6;</code>
     * @return The bytes for region.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 7;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 7;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATTITUDE_FIELD_NUMBER = 8;
    private float lattitude_ = 0F;
    /**
     * <code>optional float lattitude = 8;</code>
     * @return Whether the lattitude field is set.
     */
    @java.lang.Override
    public boolean hasLattitude() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional float lattitude = 8;</code>
     * @return The lattitude.
     */
    @java.lang.Override
    public float getLattitude() {
      return lattitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 9;
    private float longitude_ = 0F;
    /**
     * <code>optional float longitude = 9;</code>
     * @return Whether the longitude field is set.
     */
    @java.lang.Override
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float longitude = 9;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public float getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(trieKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, trieKey_);
      }
      if (beginIp_ != 0L) {
        output.writeInt64(2, beginIp_);
      }
      if (endIp_ != 0L) {
        output.writeInt64(3, endIp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cc_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cc_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, country_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, region_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, city_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeFloat(8, lattitude_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(9, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(trieKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, trieKey_);
      }
      if (beginIp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, beginIp_);
      }
      if (endIp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endIp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cc_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cc_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, country_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, region_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, city_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, lattitude_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GeoIpRecordOuterClass.GeoIpRecord)) {
        return super.equals(obj);
      }
      GeoIpRecordOuterClass.GeoIpRecord other = (GeoIpRecordOuterClass.GeoIpRecord) obj;

      if (!getTrieKey()
          .equals(other.getTrieKey())) return false;
      if (getBeginIp()
          != other.getBeginIp()) return false;
      if (getEndIp()
          != other.getEndIp()) return false;
      if (!getCc()
          .equals(other.getCc())) return false;
      if (!getCountry()
          .equals(other.getCountry())) return false;
      if (!getRegion()
          .equals(other.getRegion())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (hasLattitude() != other.hasLattitude()) return false;
      if (hasLattitude()) {
        if (java.lang.Float.floatToIntBits(getLattitude())
            != java.lang.Float.floatToIntBits(
                other.getLattitude())) return false;
      }
      if (hasLongitude() != other.hasLongitude()) return false;
      if (hasLongitude()) {
        if (java.lang.Float.floatToIntBits(getLongitude())
            != java.lang.Float.floatToIntBits(
                other.getLongitude())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRIE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getTrieKey().hashCode();
      hash = (37 * hash) + BEGIN_IP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBeginIp());
      hash = (37 * hash) + END_IP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndIp());
      hash = (37 * hash) + CC_FIELD_NUMBER;
      hash = (53 * hash) + getCc().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      if (hasLattitude()) {
        hash = (37 * hash) + LATTITUDE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLattitude());
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLongitude());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GeoIpRecordOuterClass.GeoIpRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GeoIpRecordOuterClass.GeoIpRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code enot.telegram.GeoIpRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:enot.telegram.GeoIpRecord)
        GeoIpRecordOuterClass.GeoIpRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GeoIpRecordOuterClass.internal_static_enot_telegram_GeoIpRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GeoIpRecordOuterClass.internal_static_enot_telegram_GeoIpRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GeoIpRecordOuterClass.GeoIpRecord.class, GeoIpRecordOuterClass.GeoIpRecord.Builder.class);
      }

      // Construct using mayton.bigdata.kafka.protobuf.GeoIpRecordOuterClass.GeoIpRecord.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        trieKey_ = "";
        beginIp_ = 0L;
        endIp_ = 0L;
        cc_ = "";
        country_ = "";
        region_ = "";
        city_ = "";
        lattitude_ = 0F;
        longitude_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GeoIpRecordOuterClass.internal_static_enot_telegram_GeoIpRecord_descriptor;
      }

      @java.lang.Override
      public GeoIpRecordOuterClass.GeoIpRecord getDefaultInstanceForType() {
        return GeoIpRecordOuterClass.GeoIpRecord.getDefaultInstance();
      }

      @java.lang.Override
      public GeoIpRecordOuterClass.GeoIpRecord build() {
        GeoIpRecordOuterClass.GeoIpRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GeoIpRecordOuterClass.GeoIpRecord buildPartial() {
        GeoIpRecordOuterClass.GeoIpRecord result = new GeoIpRecordOuterClass.GeoIpRecord(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(GeoIpRecordOuterClass.GeoIpRecord result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.trieKey_ = trieKey_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.beginIp_ = beginIp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.endIp_ = endIp_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cc_ = cc_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.country_ = country_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.region_ = region_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.city_ = city_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.lattitude_ = lattitude_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.longitude_ = longitude_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GeoIpRecordOuterClass.GeoIpRecord) {
          return mergeFrom((GeoIpRecordOuterClass.GeoIpRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GeoIpRecordOuterClass.GeoIpRecord other) {
        if (other == GeoIpRecordOuterClass.GeoIpRecord.getDefaultInstance()) return this;
        if (!other.getTrieKey().isEmpty()) {
          trieKey_ = other.trieKey_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getBeginIp() != 0L) {
          setBeginIp(other.getBeginIp());
        }
        if (other.getEndIp() != 0L) {
          setEndIp(other.getEndIp());
        }
        if (!other.getCc().isEmpty()) {
          cc_ = other.cc_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getRegion().isEmpty()) {
          region_ = other.region_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.hasLattitude()) {
          setLattitude(other.getLattitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                trieKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                beginIp_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                endIp_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                cc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                country_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                region_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 69: {
                lattitude_ = input.readFloat();
                bitField0_ |= 0x00000080;
                break;
              } // case 69
              case 77: {
                longitude_ = input.readFloat();
                bitField0_ |= 0x00000100;
                break;
              } // case 77
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object trieKey_ = "";
      /**
       * <code>string trie_key = 1;</code>
       * @return The trieKey.
       */
      public java.lang.String getTrieKey() {
        java.lang.Object ref = trieKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          trieKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string trie_key = 1;</code>
       * @return The bytes for trieKey.
       */
      public com.google.protobuf.ByteString
          getTrieKeyBytes() {
        java.lang.Object ref = trieKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trieKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string trie_key = 1;</code>
       * @param value The trieKey to set.
       * @return This builder for chaining.
       */
      public Builder setTrieKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        trieKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string trie_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrieKey() {
        trieKey_ = getDefaultInstance().getTrieKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string trie_key = 1;</code>
       * @param value The bytes for trieKey to set.
       * @return This builder for chaining.
       */
      public Builder setTrieKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        trieKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long beginIp_ ;
      /**
       * <code>int64 begin_ip = 2;</code>
       * @return The beginIp.
       */
      @java.lang.Override
      public long getBeginIp() {
        return beginIp_;
      }
      /**
       * <code>int64 begin_ip = 2;</code>
       * @param value The beginIp to set.
       * @return This builder for chaining.
       */
      public Builder setBeginIp(long value) {
        
        beginIp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 begin_ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBeginIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        beginIp_ = 0L;
        onChanged();
        return this;
      }

      private long endIp_ ;
      /**
       * <code>int64 end_ip = 3;</code>
       * @return The endIp.
       */
      @java.lang.Override
      public long getEndIp() {
        return endIp_;
      }
      /**
       * <code>int64 end_ip = 3;</code>
       * @param value The endIp to set.
       * @return This builder for chaining.
       */
      public Builder setEndIp(long value) {
        
        endIp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 end_ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endIp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object cc_ = "";
      /**
       * <code>string cc = 4;</code>
       * @return The cc.
       */
      public java.lang.String getCc() {
        java.lang.Object ref = cc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cc = 4;</code>
       * @return The bytes for cc.
       */
      public com.google.protobuf.ByteString
          getCcBytes() {
        java.lang.Object ref = cc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cc = 4;</code>
       * @param value The cc to set.
       * @return This builder for chaining.
       */
      public Builder setCc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cc_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string cc = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCc() {
        cc_ = getDefaultInstance().getCc();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string cc = 4;</code>
       * @param value The bytes for cc to set.
       * @return This builder for chaining.
       */
      public Builder setCcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cc_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 5;</code>
       * @return The country.
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 5;</code>
       * @return The bytes for country.
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 5;</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        country_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        country_ = getDefaultInstance().getCountry();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string country = 5;</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        country_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object region_ = "";
      /**
       * <code>string region = 6;</code>
       * @return The region.
       */
      public java.lang.String getRegion() {
        java.lang.Object ref = region_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          region_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string region = 6;</code>
       * @return The bytes for region.
       */
      public com.google.protobuf.ByteString
          getRegionBytes() {
        java.lang.Object ref = region_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          region_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string region = 6;</code>
       * @param value The region to set.
       * @return This builder for chaining.
       */
      public Builder setRegion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        region_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string region = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegion() {
        region_ = getDefaultInstance().getRegion();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string region = 6;</code>
       * @param value The bytes for region to set.
       * @return This builder for chaining.
       */
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        region_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 7;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 7;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 7;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 7;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private float lattitude_ ;
      /**
       * <code>optional float lattitude = 8;</code>
       * @return Whether the lattitude field is set.
       */
      @java.lang.Override
      public boolean hasLattitude() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional float lattitude = 8;</code>
       * @return The lattitude.
       */
      @java.lang.Override
      public float getLattitude() {
        return lattitude_;
      }
      /**
       * <code>optional float lattitude = 8;</code>
       * @param value The lattitude to set.
       * @return This builder for chaining.
       */
      public Builder setLattitude(float value) {
        
        lattitude_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional float lattitude = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLattitude() {
        bitField0_ = (bitField0_ & ~0x00000080);
        lattitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>optional float longitude = 9;</code>
       * @return Whether the longitude field is set.
       */
      @java.lang.Override
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional float longitude = 9;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional float longitude = 9;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional float longitude = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000100);
        longitude_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:enot.telegram.GeoIpRecord)
    }

    // @@protoc_insertion_point(class_scope:enot.telegram.GeoIpRecord)
    private static final GeoIpRecordOuterClass.GeoIpRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GeoIpRecordOuterClass.GeoIpRecord();
    }

    public static GeoIpRecordOuterClass.GeoIpRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeoIpRecord>
        PARSER = new com.google.protobuf.AbstractParser<GeoIpRecord>() {
      @java.lang.Override
      public GeoIpRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GeoIpRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeoIpRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GeoIpRecordOuterClass.GeoIpRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_enot_telegram_GeoIpRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_enot_telegram_GeoIpRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&src/main/resources/geo-ip-record.proto" +
      "\022\renot.telegram\"\317\001\n\013GeoIpRecord\022\020\n\010trie_" +
      "key\030\001 \001(\t\022\020\n\010begin_ip\030\002 \001(\003\022\016\n\006end_ip\030\003 " +
      "\001(\003\022\n\n\002cc\030\004 \001(\t\022\017\n\007country\030\005 \001(\t\022\016\n\006regi" +
      "on\030\006 \001(\t\022\014\n\004city\030\007 \001(\t\022\026\n\tlattitude\030\010 \001(" +
      "\002H\000\210\001\001\022\026\n\tlongitude\030\t \001(\002H\001\210\001\001B\014\n\n_latti" +
      "tudeB\014\n\n_longitudeJ\005\010\n\020\311\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_enot_telegram_GeoIpRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_enot_telegram_GeoIpRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_enot_telegram_GeoIpRecord_descriptor,
        new java.lang.String[] { "TrieKey", "BeginIp", "EndIp", "Cc", "Country", "Region", "City", "Lattitude", "Longitude", "Lattitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
