@startuml
object Server
object ServerConnector
object SocketConnector
object ServletContextHandler
object ResourceHandler
object HandlerCollection
object DefaultHandler
object ContextHandler
object RequestLog

Server *-- ContextHandler
Server o-- SocketConnector
Server o-- ServerConnector
Server *-- HandlerCollection
Server *-- RequestLog
HandlerCollection o-- ResourceHandler
HandlerCollection o-- ServletContextHandler
HandlerCollection o-- DefaultHandler

@enduml
